language: node_js
node_js:
  - node
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - ~/.cache
jobs:
  include:
    - stage: Tests
      name: Run All Tests
      before_script:
        - yarn build
      script:
        - yarn ci
        - yarn lint